### ISSUE TITLE
Fatal Exception: java.lang.IllegalStateException

### ISSUE THREAD

**Issue by mengoni** [Ogury/sdk-integrations#20]
Hi, I've got several hundreds of crash on my app related on the Ogury Android SDK.

Here is the raw report:
Fatal Exception: java.lang.IllegalStateException
       at android.media.MediaPlayer.isPlaying(MediaPlayer.java)
       at io.presage.formats.multiwebviews.video.a.g(SourceFile:203)
       at io.presage.formats.multiwebviews.video.a.surfaceDestroyed(SourceFile:92)
       at android.view.SurfaceView.updateWindow(SurfaceView.java:704)
       at android.view.SurfaceView.onWindowVisibilityChanged(SurfaceView.java:322)
       at android.view.View.dispatchWindowVisibilityChanged(View.java:10454)
       at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1330)
       at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1330)
       at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1330)
       at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1330)
       at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1330)
       at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1330)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1841)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1528)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7564)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
       at android.view.Choreographer.doCallbacks(Choreographer.java:686)
       at android.view.Choreographer.doFrame(Choreographer.java:622)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:7331)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by Vdeub** [comment]
Issues shouldn't be opened on this project.
Please contact techsupport@ogury.co if you have any issues.
Thanks
