### ISSUE TITLE
[NPE] io.presage.formats.m 1.8.1

### ISSUE THREAD

**Issue by JonathanMercandalli** [Ogury/sdk-integrations#21]
Since the last bump to 1.8.1, we have an NPE.

```
Fatal Exception: java.lang.NullPointerException
       at io.presage.formats.m.run(SourceFile:209)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:146)
       at android.app.ActivityThread.main(ActivityThread.java:5653)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

---

(decompiled code of "m" class below)
```java
final class m implements Runnable {
    m(i var1) {
        this.a = var1;
    }

    public final void run() {
        WindowManager var1 = (WindowManager)this.a.h().getSystemService("window");
        if(this.a.e() != null) {
            try {
                Iterator var2 = this.a.e().iterator();

                while(var2.hasNext()) {
                    b var3 = (b)var2.next();
                    var1.removeView(var3.b());
                }

                return;
            } catch (IllegalArgumentException var4) {
                i.k().warn(String.format("%s hideAd error: %s", new Object[]{"Ad", var4.toString()}));
            }
        }

    }
}
```

----

Please let me know if you need additional information to fix this crash.

**Comment by Vdeub** [comment]
Issues shouldn't be opened on this project.
You will be contacted by the tech support team.
Thanks.
